# Generated by Django 5.1.1 on 2024-09-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
